# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - '*'
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - shell: bash
        id: create_release
        env:
          HOST: 'https://api.tracker.yandex.net'
          YA_TOKEN: ${{ secrets.YA_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: |
          sh ./.github/workflows/scripts/release.sh
            echo $CLIENT_ID HOST=$HOST
            echo 'Thats all folks'
